// packages/solid/src/actor.ts
/**
 * @module @doeixd/solid/actor
 *
 * Provides a React-like `useActor` hook for integrating component-owned state
 * engines from `@doeixd/events` (like Actors or Reducers) into SolidJS components.
 */

import { createSignal, createEffect, onCleanup } from 'solid-js';
import { createStore as createSolidStore, reconcile } from 'solid-js/store';

/**
 * A generic interface for a store-like object from @doeixd/events.
 */
interface ActorLike<TState, TActions> {
  (): TState;
  subscribe: (callback: (value: TState) => void) => () => void;
  // This is a stand-in for a reducer's `dispatch` or an actor's own methods
  [key: string]: any;
}

/**
 * A SolidJS hook that creates and manages a component-owned instance of an
 * `@doeixd/events` actor or reducer.
 *
 * It provides a `[state, actions]` tuple, similar to React's `useReducer` or
 * our own `useActor` for React, making the API familiar across frameworks. It
 * subscribes to the external store and syncs its state to a fine-grained
 * Solid store for optimal performance.
 *
 * @param actorFactory A factory function that creates and returns the actor instance
 *   (e.g., `() => createFormStore()`). In Solid, this runs only once.
 * @returns A tuple `[state, actions]`, where `state` is a reactive Solid store
 *   and `actions` is a stable object of the actor's methods.
 *
 * @example
 * import { useActor } from '@doeixd/solid';
 * import { createCounterActor } from './counterActor';
 *
 * function CounterComponent() {
  *   // Create and adapt the actor in one idiomatic line.
  *   const [state, actions] = useActor(createCounterActor);
  *
  *   // `state` is now a fine-grained Solid store.
  *   // `actions` contains stable methods like `increment`.
  *
  *   return (
  *     <div>
  *       <p>Count: {state.count}</p>
  *       <button onClick={() => actions.increment()}>Increment</button>
  *     </div>
  *   );
  * }
 */
export function useActor<
  TState extends object,
  TActions extends object,
  TActor extends ActorLike<TState, TActions>
>(
  actorFactory: () => TActor
): [TState, TActions] {
  // 1. In Solid, the component body runs once, so we can create the instance directly.
  const initialInstance = actorFactory();

  // 2. Use a signal to track the *current* immutable instance of the store.
  // This is essential for createReducer, which returns a new instance on every dispatch.
  const [instance, setInstance] = createSignal(initialInstance);

  // 3. Create a fine-grained Solid store to hold the reactive state.
  const [state, setState] = createSolidStore(instance()());

  // 4. Create an effect that subscribes to the current store instance.
  createEffect(() => {
    const currentInstance = instance();
    const unsubscribe = currentInstance.subscribe((newState) => {
      // Use `reconcile` for efficient, deep updates to the Solid store.
      setState(reconcile(newState));
    });
    // The effect's cleanup automatically handles unsubscription.
    onCleanup(unsubscribe);
  });

  // 5. Create a stable actions object that is safe to use in event handlers.
  const actions = {} as TActions;
  const actionMethods = initialInstance.dispatch || initialInstance.actions || initialInstance;

  for (const key in actionMethods) {
    if (typeof actionMethods[key] === 'function' && key !== 'subscribe') {
      (actions as any)[key] = (...args: any[]) => {
        // Always get the LATEST instance from the signal before dispatching.
        const currentStore = instance();
        const result = (currentStore.dispatch || currentStore.actions || currentStore)[key](...args);

        // If the action returned a new store instance (i.e., it was a reducer),
        // update our instance signal. This will trigger the effect to re-subscribe.
        if (result && typeof result.subscribe === 'function') {
          setInstance(result as any);
        }
      };
    }
  }

  return [state, actions];
}

// packages/react/src/actor.ts
/**
 * @module @doeixd/react/actor
 *
 * Provides React hooks for creating and subscribing to component-owned instances
 * of stateful engines from `@doeixd/events` (like Actors, Reducers, or State Machines).
 *
 * These hooks are the ideal primitives for when a component "owns" a piece of
 * complex, non-React state logic.
 */

import { useState, useSyncExternalStore } from 'react';

/**
 * A generic interface describing the shape of a stateful object
 * from @doeixd/events (e.g., an Actor or a Reducer store).
 * It must have a subscribe method and be callable to get its current state.
 * @template TState The shape of the state object.
 */
interface SubscribableWithValue<TState> {
  (value?: TState): TState;
  subscribe: (callback: (value: TState) => void) => () => void;
}

/**
 * Creates a stable, component-bound instance of a stateful actor/store and
 * subscribes to its state, triggering re-renders on updates.
 *
 * This hook is the canonical way to integrate a stateful `@doeixd/events`
 * primitive whose lifecycle is tied to a specific component. It uses React's
 * `useSyncExternalStore` for a robust and performant subscription.
 *
 * @template TState The type of the actor's state.
 * @template TActor The type of the actor instance.
 * @param actorFactory A factory function that creates and returns the actor instance (e.g., `() => createCounterActor()`).
 *   The factory is called only once on the component's initial render.
 * @returns A tuple `[state, actor]`, where `state` is the reactive state and `actor` is the stable instance.
 *
 * @example
 * import { useActor } from '@doeixd/react';
 * import { createCounterActor } from './counterActor';
 *
 * function CounterComponent() {
 *   // The counter actor's lifecycle is now tied to this component.
 *   const [counterState, counterActor] = useActor(createCounterActor);
 *
 *   return (
 *     <div>
 *       <p>Count: {counterState.count}</p>
 *       <button onClick={() => counterActor.increment(1)}>Increment</button>
 *     </div>
 *   );
 * }
 */
export function useActor<
  TState extends object,
  TActor extends SubscribableWithValue<TState>
>(actorFactory: () => TActor): [TState, TActor] {
  // 1. Create a stable instance of the actor that persists for the
  // component's entire lifecycle. `useState`'s initializer ensures this runs only once.
  const [actor] = useState(actorFactory);

  // 2. Subscribe to the external actor's state using React's canonical hook.
  const state = useSyncExternalStore(
    (onStoreChange) => actor.subscribe(onStoreChange), // How to subscribe
    () => actor() // How to get a snapshot of the current state
  );

  return [state, actor];
}

/**
 * An optimized version of `useActor` that only triggers a re-render when a
 * selected part of the actor's state changes.
 *
 * This is essential for performance when a component only depends on a small
 * slice of a large state object.
 *
 * @template TState The type of the actor's state.
 * @template TActor The type of the actor instance.
 * @template TSelection The type of the selected value.
 * @param actorFactory A factory function that creates the actor instance.
 * @param selector A function that selects a value from the actor's state.
 * @returns The selected reactive state value.
 *
 * @example
 * import { useActorSelector } from '@doeixd/react';
 * import { createUserProfileActor } from './userProfileActor';
 *
 * function UserNameDisplay() {
 *   // This component will ONLY re-render when `user.name` changes.
 *   const userName = useActorSelector(
 *     createUserProfileActor,
 *     (state) => state.user.name
 *   );
 *
 *   return <h1>{userName}</h1>;
 * }
 */
export function useActorSelector<
  TState extends object,
  TActor extends SubscribableWithValue<TState>,
  TSelection
>(
  actorFactory: () => TActor,
  selector: (state: TState) => TSelection
): TSelection {
  const [actor] = useState(actorFactory);

  // useSyncExternalStore is smart enough to only re-render if the
  // return value of the `getSnapshot` function changes.
  const selectedState = useSyncExternalStore(
    (onStoreChange) => actor.subscribe(onStoreChange),
    () => selector(actor()) // The snapshot is now the selected value
  );

  return selectedState;
}
